version: '3.4'
services:
    web:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/laravel
        ports:
            - "8000:80"
        links:
            - app
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/laravel
        links:
          - mysql
    mysql:
        restart: always
        image: mysql:latest
        volumes:
            - /tmp/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=stylebdev"
        ports:
            - "3306:3306"
    mailhog:
      image: mailhog/mailhog
      ports:
        - "8025:8025"
